package alpvax.characteroverhaul.core;

import java.util.function.Function;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import alpvax.characteroverhaul.api.ability.Ability;
import alpvax.characteroverhaul.api.character.ICharacter;
import alpvax.characteroverhaul.capabilities.CapabilityCharacterHandler;
import alpvax.characteroverhaul.command.CharacterCommand;
import alpvax.characteroverhaul.core.proxy.CommonProxy;
import alpvax.characteroverhaul.core.util.ObjectFactoryRegistry;
import alpvax.characteroverhaul.network.CharacterNetwork;
import net.minecraft.client.resources.I18n;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInterModComms;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;

@Mod(modid = CharacterOverhaulMod.MOD_ID, version = CharacterOverhaulMod.VERSION, guiFactory = "alpvax.characteroverhaul.client.COGuiFactory")
public class CharacterOverhaulMod
{
	public static final String MOD_ID = "characteroverhaul";
	public static final String VERSION = "@VERSION@";//CharacterOverhaulReference.MOD_VERSION;

	@SidedProxy(
			clientSide = "alpvax.characteroverhaul.core.proxy.ClientProxy",
			serverSide = "alpvax.characteroverhaul.core.proxy.ServerProxy")
	public static CommonProxy proxy;

	@Mod.Instance(MOD_ID)
	public static CharacterOverhaulMod instance;

	@Metadata(MOD_ID)
	public static ModMetadata meta;

	//public static Configuration config;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.name = I18n.format("mod." + MOD_ID + ".name");
		meta.description = I18n.format("mod." + MOD_ID + ".description");
		meta.authorList.add("Alpvax");
		meta.autogenerated = false;

		proxy.registerPre(e);

		CharacterNetwork.init();

		//TODO:NetworkRegistry.INSTANCE.registerGuiHandler(instance, new CharacterGuiHandler());

		CapabilityCharacterHandler.register();

		//MinecraftForge.EVENT_BUS.register(instance);
		MinecraftForge.EVENT_BUS.register(new CharacterOverhaulHooks());
		//Config.load(e);
	}

	@Mod.EventHandler
	public void serverLoad(FMLServerStartingEvent event)
	{
		event.registerServerCommand(new CharacterCommand());
	}

	@Mod.EventHandler
	public void handleIMCMessage(FMLInterModComms.IMCEvent event)
	{
		for(FMLInterModComms.IMCMessage message : event.getMessages())
		{
			Matcher m = Pattern.compile("^registerAbilityFactory:(\\w+)", Pattern.CASE_INSENSITIVE).matcher(message.key);
			if(m.matches() && message.isFunctionMessage())
			{
				Function<ICharacter, Ability> func = message.getFunctionValue(ICharacter.class, Ability.class).get();
				ObjectFactoryRegistry.addFactory(Ability.class, m.group(1), func);
			}
			/*if("addCharacterCreationGuiPage".equalsIgnoreCase(message.key) && message.isStringMessage())
			{
				try
				{
					proxy.registerCreationGUIHandler(Class.forName(message.getStringValue()));
				}
				catch(ClassNotFoundException e)
				{
					//TODO:Log error
				}
			}*/
			/*if("addTabsToGui".equalsIgnoreCase(message.key))
			{
				if(message.isFunctionMessage())
				{
					proxy.registerTabGUIHandler(message);
				}
			}
			if("addCustomTabLayout".equalsIgnoreCase(message.key))
			{
				if(message.isFunctionMessage())
				{
					proxy.registerTabLayoutHandler(message);
				}
			}*/
		}
	}
}
