package alpvax.characteroverhaul.core;

import static alpvax.characteroverhaul.api.Reference.MOD_ID;

import alpvax.characteroverhaul.api.Reference;
import alpvax.characteroverhaul.capabilities.CapabilityCharacterHandler;
import alpvax.characteroverhaul.core.proxy.CommonProxy;
import net.minecraft.client.resources.I18n;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Reference.MOD_ID, version = Reference.VERSION)
public class CharacterOverhaul
{
	@SidedProxy(
			clientSide = "alpvax.characteroverhaul.core.proxy.ClientProxy",
			serverSide = "alpvax.characteroverhaul.core.proxy.CommonProxy")
	public static CommonProxy proxy;

	@Mod.Instance(MOD_ID)
	public static CharacterOverhaul instance;

	@Metadata(MOD_ID)
	public static ModMetadata meta;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.name = I18n.format("mod." + MOD_ID + ".name");
		meta.description = I18n.format("mod." + MOD_ID + ".description");
		meta.authorList.add("Alpvax");
		meta.autogenerated = false;

		proxy.registerPre();

		CapabilityCharacterHandler.register();
		MinecraftForge.EVENT_BUS.register(new CharacterOverhaulHooks());
	}
}
